config/routes.rb
Rails.application.routes.draw do

  root "notes#index"

  devise_for :users, controllers: { registrations: 'users/registrations' } 
  
  resources :users do
    post 'follow', on: :member, to: 'follows#create'
    delete 'unfollow', on: :member, to: 'follows#destroy'
  end
  
  resources :notes do
    post 'like', on: :member, to: 'likes#create'
    delete 'unlike', on: :member, to: 'likes#destroy'
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :likes
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @notes = Note.all.order("created_at DESC")
    @users = User.all.order("username ASC")
    if current_user
      @follows = Follow.where(follower_id: current_user.id)
    end
  end

  def new
    @note = Note.new
  end

  def create
    note = current_user.notes.new(note_params)
    note.save
    redirect_to notes_path
  end

  def destroy;
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  def edit; 
    @note = Note.find(params[:id])
  end

  def update;
    note = Note.find(params[:id])
    if note.update(note_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.erb
<div class="note_list">
  <h3>Notes Feed</h3>
  <% @notes.each do |note| %>
    <% if current_user %>
      <% if Follow.find_by(following_id: note.user, follower_id: current_user) %>
        <div>
          <%= note.title %> <br>
          <%= note.body %> <br>
          <%= note.user.username %> <br>

          <% if current_user == note.user %>
            <%= link_to 'Edit', edit_note_path(note) %>
            <%= link_to 'Delete', note_path(note), method: :delete, data: {confirm:"Are you sure?"} %>
          <% else %>
            <% if Like.find_by(note: note, user: current_user) %>
              <%= link_to 'Unlike', unlike_note_path(note), remote: true, method: :delete %>
            <% else %>
              <%= link_to 'Like', like_note_path(note), remote: true, method: :post if note.user != current_user %>
            <% end %>
            <%= link_to 'Unfollow', unfollow_user_path(note.user_id), remote: true, method: :delete %>
          <% end %>
        </div>
      <br><hr><br>
      <% end %>
      
    <% else %>
      <div>
        <%= note.title %> <br>
        <%= note.body %> <br>
        <%= note.user.username %> <br>
      </div>
      <br><hr><br>
    <% end %>
  <% end %>
</div>

<div class="side_list">
  <% if current_user %>
    <h3>My Follow List</h3>
    <% if @follows == nil || @follows.size == 0 %>
      <div>No User You Are Following</div>
    <% else %>
      <% @follows.each do |follow| %>
        <div>
          <%= follow.following.username %>
          <%= link_to 'Unfollow', unfollow_user_path(follow.following.id), remote: true, method: :delete %>
          <br>
      <% end %>
      <hr>
    <% end %>
    <h3>Users To Follow</h3>
    <% @users.each do |user| %>
      <% if Follow.find_by(following_id: user, follower_id: current_user) %>
      <% else %>
        <%= user.username %>
        <%= link_to 'Follow', follow_user_path(user), remote: true, method: :post %>
        <br>
      <% end%>
    <% end %>
  <% else %>
    <h3>Users List</h3>
    <% @users.each do |user| %>
      <%= user.username %> <br>
    <% end %>
  <% end %>
</div>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>

<%= form_for @note, url: note_path, method: :put do |note| %>
  <%= note.text_field :title, :maxlength => 140, placeholder: "Type your title here!"  %> <br><br>
  <%= note.text_area :body, :maxlength => 300, size: "140x10", placeholder: "Type your note here!"%> <br><br>
  <%= note.submit %>
<% end %>
<br>
<input type="button" value="Go back!" onclick="history.back()">

app/views/notes/index.html.erb
<h1>Notes Index</h1>

<div id="notes">
  <%= render partial: "note" %>
</div>

app/views/notes/index.js.erb
$('#notes').append('<%= escape_javascript render(@notes) %>');

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= form_for @note, url: notes_path, method: :post do |note| %>
  <%= note.text_field :title, :maxlength => 140, placeholder: "Type your title here!"  %> <br><br>
  <%= note.text_area :body, :maxlength => 300, size: "140x10", placeholder: "Type your note here!"%> <br><br>
  <%= note.submit %>
<% end %>
<br>
<input type="button" value="Go back!" onclick="history.back()">